
[[grammar]]
name = "r"
source = { git = "https://github.com/r-lib/tree-sitter-r", rev = "main" }


[[language]]
name = "markdown"
file-types = ["md", "markdown", "txt"]
text-width = 75
soft-wrap.wrap-at-text-width = true
language-servers = ["marksman", "markdown-oxide", "harper-ls"]


[[language]]
name = "r"
scope = "source.r"
injection-regex = "r"
file-types = ["r", "R", "Rmd", "rmd"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
grammar = "r"  # For tree-sitter support

[language-server.r-language-server]
command = "R"
args = ["--slave", "-e", "languageserver::run()"]

[[language.language-servers]]
name = "r-language-server"

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]


[language-server.harper-ls.config.harper-ls]
userDictPath = "~/.config/userdict"
fileDictPath = ""
diagnosticSeverity = "warning"
isolateEnglish = false
dialect = "American"

[language-server.harper-ls.config.harper-ls.linters]
SpellCheck = true
SpelledNumbers = false
AnA = true
SentenceCapitalization = true
UnclosedQuotes = true
WrongQuotes = false
LongSentences = true
RepeatedWords = true
Spaces = true
Matcher = true
CorrectNumberSuffix = true
